/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.*;

/**
 *
 * @author Ramon
 */
public class jfTelaPrincipal extends javax.swing.JFrame {

    private Object TelaCadastrarPersonagem;
    //private Object jDesktopPane1;

    /**
     * Creates new form jfTelaPrincipal
     */
    public jfTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMSistema = new javax.swing.JMenu();
        jMCadastrarArma = new javax.swing.JMenuItem();
        jMCadastrarArmadura = new javax.swing.JMenuItem();
        jMenuCadastrarClasse = new javax.swing.JMenuItem();
        jMCadastrarDivindade = new javax.swing.JMenuItem();
        jMCadastrarMagia = new javax.swing.JMenuItem();
        jMCadastrarPericia = new javax.swing.JMenuItem();
        jMCadastrarRaça = new javax.swing.JMenuItem();
        jMCadastrarTalento = new javax.swing.JMenuItem();
        jMPersonagens = new javax.swing.JMenu();
        jMCadastrarPersonagem = new javax.swing.JMenuItem();
        jMExportar = new javax.swing.JMenuItem();
        jMImportar = new javax.swing.JMenuItem();
        jMGerarPDF = new javax.swing.JMenuItem();
        jMIniciativa = new javax.swing.JMenu();
        jMCadastrarCampanha = new javax.swing.JMenuItem();
        jMVisualizarCalendario = new javax.swing.JMenuItem();
        jMSIniciativa = new javax.swing.JMenuItem();
        jMSons = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMTestes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SARPG");
        setExtendedState(MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(300, 300));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMSistema.setText("Sistema");

        jMCadastrarArma.setText("Cadastrar Arma");
        jMCadastrarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarArmaActionPerformed(evt);
            }
        });
        jMSistema.add(jMCadastrarArma);

        jMCadastrarArmadura.setText("Cadastrar Armadura");
        jMSistema.add(jMCadastrarArmadura);

        jMenuCadastrarClasse.setText("Cadastrar Classe");
        jMenuCadastrarClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarClasseActionPerformed(evt);
            }
        });
        jMSistema.add(jMenuCadastrarClasse);

        jMCadastrarDivindade.setText("Cadastrar Divindade");
        jMCadastrarDivindade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarDivindadeActionPerformed(evt);
            }
        });
        jMSistema.add(jMCadastrarDivindade);

        jMCadastrarMagia.setText("Cadastrar Magia");
        jMCadastrarMagia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarMagiaActionPerformed(evt);
            }
        });
        jMSistema.add(jMCadastrarMagia);

        jMCadastrarPericia.setText("Cadastrar Perícia");
        jMSistema.add(jMCadastrarPericia);

        jMCadastrarRaça.setText("Cadastrar Raça");
        jMSistema.add(jMCadastrarRaça);

        jMCadastrarTalento.setText("Cadastrar Talento");
        jMCadastrarTalento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarTalentoActionPerformed(evt);
            }
        });
        jMSistema.add(jMCadastrarTalento);

        jMenuBar1.add(jMSistema);

        jMPersonagens.setText("Personagem");
        jMPersonagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPersonagensActionPerformed(evt);
            }
        });

        jMCadastrarPersonagem.setText("Cadastrar");
        jMCadastrarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarPersonagemActionPerformed(evt);
            }
        });
        jMPersonagens.add(jMCadastrarPersonagem);

        jMExportar.setText("Exportar");
        jMExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExportarActionPerformed(evt);
            }
        });
        jMPersonagens.add(jMExportar);

        jMImportar.setText("Importar");
        jMImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMImportarActionPerformed(evt);
            }
        });
        jMPersonagens.add(jMImportar);

        jMGerarPDF.setText("Gerar PDF");
        jMGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGerarPDFActionPerformed(evt);
            }
        });
        jMPersonagens.add(jMGerarPDF);

        jMenuBar1.add(jMPersonagens);

        jMIniciativa.setText("Campanha");
        jMIniciativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIniciativaActionPerformed(evt);
            }
        });

        jMCadastrarCampanha.setText("Cadastrar Campanha");
        jMCadastrarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarCampanhaActionPerformed(evt);
            }
        });
        jMIniciativa.add(jMCadastrarCampanha);

        jMVisualizarCalendario.setText("Visualizar caledário");
        jMIniciativa.add(jMVisualizarCalendario);

        jMSIniciativa.setText("Iniciativa");
        jMSIniciativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSIniciativaActionPerformed(evt);
            }
        });
        jMIniciativa.add(jMSIniciativa);

        jMSons.setText("Sons");
        jMSons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSonsActionPerformed(evt);
            }
        });
        jMIniciativa.add(jMSons);

        jMenuBar1.add(jMIniciativa);

        jMenu4.setText("Sobre");

        jMTestes.setText("Teste");
        jMTestes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTestesActionPerformed(evt);
            }
        });
        jMenu4.add(jMTestes);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadastrarTalentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarTalentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMCadastrarTalentoActionPerformed

    private void jMCadastrarMagiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarMagiaActionPerformed
        TelaCadastrarMagia tela = new TelaCadastrarMagia();
        jDesktopPane1.add(tela);
        tela.setClosable(true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMCadastrarMagiaActionPerformed

    private void jMenuCadastrarClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrarClasseActionPerformed

    private void jMGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGerarPDFActionPerformed
        TelaExportarImportar tela = new TelaExportarImportar(true,true);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_jMGerarPDFActionPerformed

    private void jMSonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSonsActionPerformed
        TelaSons tela = new TelaSons();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_jMSonsActionPerformed

    private void jMCadastrarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarArmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMCadastrarArmaActionPerformed

    private void jMCadastrarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarPersonagemActionPerformed
        TelaCadastrarPersonagem tela = new TelaCadastrarPersonagem();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_jMCadastrarPersonagemActionPerformed

    private void jMExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExportarActionPerformed
        TelaExportarImportar tela = new TelaExportarImportar(true,false);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);        
    }//GEN-LAST:event_jMExportarActionPerformed

    private void jMPersonagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPersonagensActionPerformed
        
    }//GEN-LAST:event_jMPersonagensActionPerformed

    private void jMSIniciativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSIniciativaActionPerformed
        TelaIniciativa tela = new TelaIniciativa();
        jDesktopPane1.add(tela);
        tela.setClosable(true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMSIniciativaActionPerformed

    private void jMImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMImportarActionPerformed
        TelaExportarImportar tela = new TelaExportarImportar(false,false);
        jDesktopPane1.add(tela);
        tela.setClosable(true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMImportarActionPerformed

    private void jMIniciativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIniciativaActionPerformed
        TelaIniciativa tela = new TelaIniciativa();
        jDesktopPane1.add(tela);
        tela.setClosable(true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMIniciativaActionPerformed

    private void jMTestesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTestesActionPerformed
        Arquivo.fun();
    }//GEN-LAST:event_jMTestesActionPerformed

    private void jMCadastrarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarCampanhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMCadastrarCampanhaActionPerformed

    private void jMCadastrarDivindadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarDivindadeActionPerformed
        TelaCadastrarDivindade tela = new TelaCadastrarDivindade();
        jDesktopPane1.add(tela);
        tela.setClosable(true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMCadastrarDivindadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTelaPrincipal().setVisible(true);
            }
        });
        
        try {
            Arquivo.escritor("1-2-3-4_1-1-1-1§Campanha com quatro personagens nível 1§akddkjasdh¢1-2-3-4_2-2-3-2§Campanha 2§akddkjasdh¢1-2-3-4_10-20-10-10§Campanha avançada§akddkjasdh¢1_4§Campanha com um personagem§akddkjasdh¢1-3-4_1-3-4§Campanha com 3§akddkjasdh¢", "campanha");
            Arquivo.escritor("1§Aramil§NEUTRO_BOM§18§20§10§10§18§10¢2§Thokk Ofir§NEUTRO§20§18§10§16§8§8¢3§Felipe§CAOTICO_BOM§18§18§10§14§14§10¢4§Theodore Miranda Flores§NEUTRO_BOM§10§20§10§18§10§18¢","personagem");
            Arquivo.escritor("Bardo§d8§NEUTRO,CAOTICO_BOM§15¢Guerreiro§d10§NEUTRO,NEUTRO_BOM§5¢Ladino§d6§CAOTICO_NEUTRO,NEUTRO§30¢","classe");
            Arquivo.escritor("Latander§10§LUZ,CURA¢Torm§17§GUERRA,ORDEM¢BANER§16§MAL,MORTE,GUERRA¢","divindade");
            Arquivo.escritor("Nome§escola§1§componentes§tempoDeExecução§alcance§efeito§duração§TRUE§FALSE","magia");
            Arquivo.escritor("5","config");
        } catch (IOException ex) {
            Logger.getLogger(jfTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMCadastrarArma;
    private javax.swing.JMenuItem jMCadastrarArmadura;
    private javax.swing.JMenuItem jMCadastrarCampanha;
    private javax.swing.JMenuItem jMCadastrarDivindade;
    private javax.swing.JMenuItem jMCadastrarMagia;
    private javax.swing.JMenuItem jMCadastrarPericia;
    private javax.swing.JMenuItem jMCadastrarPersonagem;
    private javax.swing.JMenuItem jMCadastrarRaça;
    private javax.swing.JMenuItem jMCadastrarTalento;
    private javax.swing.JMenuItem jMExportar;
    private javax.swing.JMenuItem jMGerarPDF;
    private javax.swing.JMenuItem jMImportar;
    private javax.swing.JMenu jMIniciativa;
    private javax.swing.JMenu jMPersonagens;
    private javax.swing.JMenuItem jMSIniciativa;
    private javax.swing.JMenu jMSistema;
    private javax.swing.JMenuItem jMSons;
    private javax.swing.JMenuItem jMTestes;
    private javax.swing.JMenuItem jMVisualizarCalendario;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrarClasse;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
