/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import controller.Classe;
import controller.EnumTendencias;
import controller.Sistema;
import model.Arquivo;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Hohenheim
 */
public class TelaCadastrarClasse extends javax.swing.JInternalFrame {

private ArrayList<EnumTendencias> gTendencias;
private ArrayList<Classe> classes;

public TelaCadastrarClasse() {
    initComponents();
    
    gTendencias = new ArrayList();
    for (EnumTendencias lTendencia : EnumTendencias.values()) {
        modeloEsquerdo.addElement(lTendencia);
    }
    
    this.classes = Sistema.getInstance().getClasse();
    DefaultTableModel model = (DefaultTableModel)tbClasses.getModel();

    for (Classe lCl : classes)
    {
        model.addRow(new Object[] {lCl.getNome(), lCl.getDadoDeVida(), lCl.getTendência(), lCl.getPontosDePericias()});
    }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jTextNome = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jTextDadoVida = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    modeloEsquerdo = new DefaultListModel();
    jListEsquerdo = new javax.swing.JList<>();
    jScrollPane2 = new javax.swing.JScrollPane();
    modeloDireito = new DefaultListModel();
    jListDireito = new javax.swing.JList<>();
    jBDireita = new javax.swing.JButton();
    jBEsquerda = new javax.swing.JButton();
    jBSalvar = new javax.swing.JButton();
    jBAtualizar = new javax.swing.JButton();
    jBDeletar = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    tbClasses = new javax.swing.JTable();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jTextPericia = new javax.swing.JTextField();
    setTitle("Classe");

    jLabel2.setText("Nome");

    jTextNome.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextNomeActionPerformed(evt);
        }
    });

    jLabel3.setText("Dado de Vida");

    jListEsquerdo.setModel(modeloEsquerdo);
    jScrollPane1.setViewportView(jListEsquerdo);

    jListDireito.setModel(modeloDireito);
    jScrollPane2.setViewportView(jListDireito);

    jBDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/right.png"))); // NOI18N
    jBDireita.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jBDireita.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SelecionarActionPerformed(evt);
        }
    });

    jBEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/left.png"))); // NOI18N
    jBEsquerda.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jBEsquerda.setPreferredSize(new java.awt.Dimension(25, 31));
    jBEsquerda.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            NaoSelecionarActionPerformed(evt);
        }
    });

    jBSalvar.setText("Salvar");
    jBSalvar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SalvarActionPerformed(evt);
        }
    });

    jBAtualizar.setText("Atualizar");
    jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBAtualizarActionPerformed(evt);
        }
    });

    jBDeletar.setText("Deletar");
    jBDeletar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBDeletarActionPerformed(evt);
        }
    });

    tbClasses.setModel(new DefaultTableModel(
    	new Object[][] {
    	},
    	new String[] {
    		"Nome", "Dado de Vida", "Pontos Pericia", "Tend\u00EAncias"
    	}
    ));
    tbClasses.getColumnModel().getColumn(0).setPreferredWidth(55);
    tbClasses.getColumnModel().getColumn(1).setPreferredWidth(70);
    tbClasses.getColumnModel().getColumn(2).setPreferredWidth(74);
    tbClasses.getColumnModel().getColumn(3).setPreferredWidth(124);
    tbClasses.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tbClassesMouseClicked(evt);
        }
    });
    jScrollPane3.setViewportView(tbClasses);

    jLabel4.setText("Tendências");
    
    jLabel5.setText("Pts Perícia");
    
    //jTextPericia.setColumns(10);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    layout.setHorizontalGroup(
    	layout.createParallelGroup(Alignment.LEADING)
    		.addGroup(layout.createSequentialGroup()
    			.addContainerGap()
    			.addGroup(layout.createParallelGroup(Alignment.LEADING)
    				.addGroup(layout.createSequentialGroup()
    					.addComponent(jLabel2)
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addComponent(jTextNome, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addComponent(jLabel3)
    					.addPreferredGap(ComponentPlacement.UNRELATED)
    					.addComponent(jTextDadoVida, GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
    				.addGroup(layout.createSequentialGroup()
    					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
    						.addGroup(layout.createSequentialGroup()
    							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
    								.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    								.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    							.addPreferredGap(ComponentPlacement.RELATED)
    							.addComponent(jTextPericia))
    						.addGroup(layout.createSequentialGroup()
    							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
    							.addPreferredGap(ComponentPlacement.RELATED)
    							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
    								.addComponent(jBDireita)
    								.addComponent(jBEsquerda, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addGroup(layout.createParallelGroup(Alignment.LEADING)
    						.addComponent(jBDeletar, GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
    						.addComponent(jBAtualizar, GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
    						.addComponent(jBSalvar, GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
    				.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
    			.addContainerGap())
    );
    layout.setVerticalGroup(
    	layout.createParallelGroup(Alignment.LEADING)
    		.addGroup(layout.createSequentialGroup()
    			.addContainerGap()
    			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
    				.addComponent(jLabel2)
    				.addComponent(jTextNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
    				.addComponent(jTextDadoVida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
    				.addComponent(jLabel3))
    			.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
    			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
    				.addComponent(jLabel5)
    				.addComponent(jTextPericia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
    			.addPreferredGap(ComponentPlacement.RELATED)
    			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
    				.addGroup(layout.createSequentialGroup()
    					.addComponent(jBDireita)
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addComponent(jBEsquerda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
    					.addGap(30))
    				.addGroup(layout.createSequentialGroup()
    					.addComponent(jBSalvar)
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addComponent(jBAtualizar)
    					.addPreferredGap(ComponentPlacement.UNRELATED)
    					.addComponent(jBDeletar)
    					.addGap(12))
    				.addGroup(layout.createSequentialGroup()
    					.addComponent(jLabel4)
    					.addPreferredGap(ComponentPlacement.RELATED)
    					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
    						.addComponent(jScrollPane2, Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
    						.addComponent(jScrollPane1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
    			.addGap(12)
    			.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
    			.addContainerGap())
    );
    getContentPane().setLayout(layout);

    pack();
}// </editor-fold>//GEN-END:initComponents

private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed

    for (Object lTendencia : jListEsquerdo.getSelectedValues()) {
        modeloDireito.addElement(lTendencia);
        gTendencias.add((EnumTendencias)lTendencia);
    }
    for (EnumTendencias lTendecia: gTendencias) {
        modeloEsquerdo.removeElement(lTendecia);
    }
}//GEN-LAST:event_SelecionarActionPerformed

private void NaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaoSelecionarActionPerformed
    for (Object lTendencia : jListDireito.getSelectedValues()) {
        modeloEsquerdo.addElement(lTendencia);
        gTendencias.remove((EnumTendencias)lTendencia);
    }

    modeloDireito.removeAllElements();
    for (EnumTendencias lTendencia : gTendencias) {
        modeloDireito.addElement(lTendencia);
    }
}//GEN-LAST:event_NaoSelecionarActionPerformed

private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
    DefaultTableModel model = (DefaultTableModel)tbClasses.getModel();
    model.addRow(new Object[] {jTextNome.getText(), jTextDadoVida.getText(), Integer.parseInt(jTextPericia.getText()), gTendencias});

    //LIMPAR CAMPOS
    gTendencias = new ArrayList();
    for (EnumTendencias lTendencia : EnumTendencias.values()) {
        modeloEsquerdo.addElement(lTendencia);
    }
    modeloDireito.removeAllElements();
    jTextNome.setText("");
    jTextDadoVida.setText("");
    jTextPericia.setText("");

    //SALVAR
    classes.clear();
    for (int i = 0; i < model.getRowCount(); i++)
    {
        Object Nome = model.getValueAt(i, 0);
        Object DadoVida = model.getValueAt(i, 1);
        Object PontosPericia = model.getValueAt(i, 2);
        Object Tendencia = model.getValueAt(i, 3);
        classes.add(new Classe(Nome.toString(), DadoVida.toString(), (ArrayList)Tendencia, Integer.parseInt(PontosPericia.toString())));
    }
    Sistema.salvar(Sistema.EnumObjeto.CLASSE);
}//GEN-LAST:event_SalvarActionPerformed

private void jBDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarActionPerformed
    DefaultTableModel model = (DefaultTableModel)tbClasses.getModel();
    classes.remove(tbClasses.getSelectedRow());
    model.removeRow(tbClasses.getSelectedRow());


    //LIMPAR CAMPOS
    gTendencias = new ArrayList();
    for (EnumTendencias lTendencia : EnumTendencias.values()) {
        modeloEsquerdo.addElement(lTendencia);
    }
    modeloDireito.removeAllElements();
    jTextNome.setText("");
    jTextDadoVida.setText("");
    jTextPericia.setText("");

    //SALVAR
    classes.clear();
    for (int i = 0; i < model.getRowCount(); i++)
    {
        Object Nome = model.getValueAt(i, 0);
        Object DadoVida = model.getValueAt(i, 1);
        Object PontosPericia = model.getValueAt(i, 2);
        Object Tendencia = model.getValueAt(i, 3);
        classes.add(new Classe(Nome.toString(), DadoVida.toString(), (ArrayList)Tendencia, Integer.parseInt(PontosPericia.toString())));
    }
    Sistema.salvar(Sistema.EnumObjeto.CLASSE);
}//GEN-LAST:event_jBDeletarActionPerformed

private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
    DefaultTableModel model = (DefaultTableModel)tbClasses.getModel();
    model.setValueAt(jTextNome.getText(), tbClasses.getSelectedRow(), 0);
    model.setValueAt(jTextDadoVida.getText(), tbClasses.getSelectedRow(), 1);
    model.setValueAt(Integer.parseInt(jTextPericia.getText()), tbClasses.getSelectedRow(), 2);
    model.setValueAt(gTendencias, tbClasses.getSelectedRow(), 3);

    //LIMPAR CAMPOS
    gTendencias = new ArrayList();
    for (EnumTendencias lTendencia : EnumTendencias.values()) {
        modeloEsquerdo.addElement(lTendencia);
    }
    modeloDireito.removeAllElements();
    jTextNome.setText("");
    jTextDadoVida.setText("");
    jTextPericia.setText("");

    //SALVAR
    classes.clear();
    for (int i = 0; i < model.getRowCount(); i++)
    {
        Object Nome = model.getValueAt(i, 0);
        Object DadoVida = model.getValueAt(i, 1);
        Object PontosPericia = model.getValueAt(i, 2);
        Object Tendencia = model.getValueAt(i, 3);
        classes.add(new Classe(Nome.toString(), DadoVida.toString(), (ArrayList)Tendencia, Integer.parseInt(PontosPericia.toString())));
    }
    Sistema.salvar(Sistema.EnumObjeto.CLASSE);
}//GEN-LAST:event_jBAtualizarActionPerformed

private void tbClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClassesMouseClicked
    DefaultTableModel model = (DefaultTableModel)tbClasses.getModel();
    jTextNome.setText(model.getValueAt(tbClasses.getSelectedRow(), 0).toString());
    jTextDadoVida.setText(model.getValueAt(tbClasses.getSelectedRow(), 1).toString());
    jTextPericia.setText(model.getValueAt(tbClasses.getSelectedRow(), 2).toString());

    Object lTendencias = model.getValueAt(tbClasses.getSelectedRow(), 3);
    gTendencias.clear();
    modeloDireito.removeAllElements();
    for (Object ld : (ArrayList)lTendencias)
    {
        modeloDireito.addElement(ld);
        gTendencias.add((EnumTendencias)ld);
    }
    for (EnumTendencias lTendencia : gTendencias) {
        modeloEsquerdo.removeElement(lTendencia);
    }
}//GEN-LAST:event_tbClassesMouseClicked

private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextNomeActionPerformed


// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton jBAtualizar;
private javax.swing.JButton jBDeletar;
private javax.swing.JButton jBDireita;
private javax.swing.JButton jBEsquerda;
private javax.swing.JButton jBSalvar;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JList<String> jListDireito;
private DefaultListModel modeloDireito;
private javax.swing.JList<String> jListEsquerdo;
private DefaultListModel modeloEsquerdo;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JScrollPane jScrollPane2;
private javax.swing.JScrollPane jScrollPane3;
private javax.swing.JTextField jTextDadoVida;
private javax.swing.JTextField jTextNome;
private javax.swing.JTextField jTextPericia;
private javax.swing.JTable tbClasses;
}
