/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import controller.Divindade;
import controller.EnumDominios;
import controller.Sistema;
import model.Arquivo;

/**
 *
 * @author PHAF
 */
public class TelaCadastrarDivindade extends javax.swing.JInternalFrame {

    private ArrayList<EnumDominios> gDominios;
    private ArrayList<Divindade> divindades;
    
    public TelaCadastrarDivindade() {
        initComponents();
       
        gDominios = new ArrayList();
        for (EnumDominios lDominio : EnumDominios.values()) {
            modeloEsquerdo.addElement(lDominio);
        }
        
        this.divindades = Sistema.getInstance().getDivindades();
        DefaultTableModel model = (DefaultTableModel)tbDivindades.getModel();
        
        for (Divindade lDiv : divindades)
        {
            model.addRow(new Object[] {lDiv.getNome(), lDiv.getPoder(), lDiv.getDominios()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNivelPoder = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeloEsquerdo = new DefaultListModel();
        jListEsquerdo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        modeloDireito = new DefaultListModel();
        jListDireito = new javax.swing.JList<>();
        jBDireita = new javax.swing.JButton();
        jBEsquerda = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBDeletar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDivindades = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Divindade");

        jLabel2.setText("Nome");

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nível de Poder");

        jListEsquerdo.setModel(modeloEsquerdo);
        jScrollPane1.setViewportView(jListEsquerdo);

        jListDireito.setModel(modeloDireito);
        jScrollPane2.setViewportView(jListDireito);

        jBDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/right.png"))); // NOI18N
        jBDireita.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarActionPerformed(evt);
            }
        });

        jBEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/left.png"))); // NOI18N
        jBEsquerda.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBEsquerda.setPreferredSize(new java.awt.Dimension(25, 31));
        jBEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaoSelecionarActionPerformed(evt);
            }
        });

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jBDeletar.setText("Deletar");
        jBDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarActionPerformed(evt);
            }
        });

        tbDivindades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Nível de Poder", "Domínios"
            }
        ));
        tbDivindades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDivindadesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDivindades);

        jLabel4.setText("Domínios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBDireita)
                            .addComponent(jBEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAtualizar)))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNivelPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNivelPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDeletar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBDireita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed
      
        for (Object lDominio : jListEsquerdo.getSelectedValues()) {
            modeloDireito.addElement(lDominio);
            gDominios.add((EnumDominios)lDominio);
        } 
       for (EnumDominios lDominio : gDominios) {
            modeloEsquerdo.removeElement(lDominio);
       } 
    }//GEN-LAST:event_SelecionarActionPerformed

    private void NaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaoSelecionarActionPerformed
       for (Object lDominio : jListDireito.getSelectedValues()) {
            modeloEsquerdo.addElement(lDominio);
            gDominios.remove((EnumDominios)lDominio);
        }
       
       modeloDireito.removeAllElements();
       for (EnumDominios lDominio : gDominios) {
            modeloDireito.addElement(lDominio);
       } 
    }//GEN-LAST:event_NaoSelecionarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbDivindades.getModel();
        model.addRow(new Object[] {jTextNome.getText(), Integer.parseInt(jTextNivelPoder.getText()), gDominios});
        
        //LIMPAR CAMPOS
        gDominios = new ArrayList();
        for (EnumDominios lDominio : EnumDominios.values()) {
            modeloEsquerdo.addElement(lDominio);
        }
        modeloDireito.removeAllElements();
        jTextNome.setText("");
        jTextNivelPoder.setText("");
        
        //SALVAR
        divindades.clear();
        for (int i = 0; i < model.getRowCount(); i++)
        {
           Object Nome = model.getValueAt(i, 0);
           Object Nivel = model.getValueAt(i, 1);
           Object Dominios = model.getValueAt(i, 2);
           divindades.add(new Divindade(Nome.toString(), Integer.parseInt(Nivel.toString()), (ArrayList)Dominios));
        }      
       Sistema.salvar(Sistema.EnumObjeto.DIVINDADE);
    }//GEN-LAST:event_SalvarActionPerformed

    private void jBDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbDivindades.getModel();
        divindades.remove(tbDivindades.getSelectedRow());
        model.removeRow(tbDivindades.getSelectedRow());

        
        //LIMPAR CAMPOS
        gDominios = new ArrayList();
        for (EnumDominios lDominio : EnumDominios.values()) {
            modeloEsquerdo.addElement(lDominio);
        }
        modeloDireito.removeAllElements();
        jTextNome.setText("");
        jTextNivelPoder.setText("");
        
        //SALVAR
        divindades.clear();
        for (int i = 0; i < model.getRowCount(); i++)
        {
           Object Nome = model.getValueAt(i, 0);
           Object Nivel = model.getValueAt(i, 1);
           Object Dominios = model.getValueAt(i, 2);
           divindades.add(new Divindade(Nome.toString(), Integer.parseInt(Nivel.toString()), (ArrayList)Dominios));
        }      
       Sistema.salvar(Sistema.EnumObjeto.DIVINDADE);
    }//GEN-LAST:event_jBDeletarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbDivindades.getModel();
        model.setValueAt(jTextNome.getText(), tbDivindades.getSelectedRow(), 0);
        model.setValueAt(Integer.parseInt(jTextNivelPoder.getText()), tbDivindades.getSelectedRow(), 1);
        model.setValueAt(gDominios, tbDivindades.getSelectedRow(), 2);     
        
        //LIMPAR CAMPOS
        gDominios = new ArrayList();
        for (EnumDominios lDominio : EnumDominios.values()) {
            modeloEsquerdo.addElement(lDominio);
        }
        modeloDireito.removeAllElements();
        jTextNome.setText("");
        jTextNivelPoder.setText("");
        
        //SALVAR
        divindades.clear();
        for (int i = 0; i < model.getRowCount(); i++)
        {
           Object Nome = model.getValueAt(i, 0);
           Object Nivel = model.getValueAt(i, 1);
           Object Dominios = model.getValueAt(i, 2);
           divindades.add(new Divindade(Nome.toString(), Integer.parseInt(Nivel.toString()), (ArrayList)Dominios));
        }      
        Sistema.salvar(Sistema.EnumObjeto.DIVINDADE);
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void tbDivindadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDivindadesMouseClicked
        DefaultTableModel model = (DefaultTableModel)tbDivindades.getModel();
        jTextNome.setText(model.getValueAt(tbDivindades.getSelectedRow(), 0).toString());
        jTextNivelPoder.setText(model.getValueAt(tbDivindades.getSelectedRow(), 1).toString());
        
        Object lDominios = model.getValueAt(tbDivindades.getSelectedRow(), 2);
        gDominios.clear();
        modeloDireito.removeAllElements();
        for (Object ld : (ArrayList)lDominios)
        {
            modeloDireito.addElement(ld);
            gDominios.add((EnumDominios)ld);
        }
        for (EnumDominios lDominio : gDominios) {
            modeloEsquerdo.removeElement(lDominio);
       }      
    }//GEN-LAST:event_tbDivindadesMouseClicked

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBDeletar;
    private javax.swing.JButton jBDireita;
    private javax.swing.JButton jBEsquerda;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListDireito;
    private DefaultListModel modeloDireito;
    private javax.swing.JList<String> jListEsquerdo;
    private DefaultListModel modeloEsquerdo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextNivelPoder;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTable tbDivindades;
    // End of variables declaration//GEN-END:variables
}
